import type { Metadata } from "next";
import "./globals.css";
import React, { ReactNode } from "react";

interface LayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const Layout = ({ children }: LayoutProps) => {
  return (
    <html lang="en">
    <body>
      <main>{children}</main>
    </body>
  </html>
  );
};

export default Layout;
